language: python
dist: bionic
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
python:
  - "3.6"
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
addons:
  apt:
    packages:
      - 2to3
