# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Private', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='group',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='info_descriptor',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='info_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='orig_release',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='partner',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='site_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Development', 'Development'), ('Active', 'Active'), ('Archived', 'Archived')], default='Development', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='thumb_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
