# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('portfolio', '0002_auto_20160715_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
