# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_entryindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='info_descriptor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='info_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orig_release',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='partner',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
