# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_entry_thumb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='access',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='info_descriptor',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='info_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='orig_release',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thumb',
        ),
    ]
