# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20151210_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmlocation',
            name='dom_0',
        ),
        migrations.RemoveField(
            model_name='vmlocation',
            name='dom_u',
        ),
        migrations.RemoveField(
            model_name='server',
            name='virtual',
        ),
        migrations.DeleteModel(
            name='VMLocation',
        ),
    ]
