# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160324_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
