# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application_deprecated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AliasContact',
        ),
    ]
