# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160418_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='sentry_name',
        ),
    ]
