# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='repo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
