# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170109_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ec2_instance_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
