# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_server_ec2_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='mac_addr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
