# Generated by Django 3.2.12 on 2022-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180123_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ('ipv4',)},
        ),
        migrations.RemoveField(
            model_name='server',
            name='operating_system',
        ),
        migrations.AlterField(
            model_name='alias',
            name='administrative_info',
            field=models.TextField(blank=True, default='', help_text="Required if not a .ccnmtl.columbia.edu hostname.Please use this field for information about where the domain is registered, what account it's set up with (don't enter passwords here though) and who handles payments, DNS changes, etc."),
        ),
        migrations.AlterField(
            model_name='alias',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('deprecated', 'deprecated')], default='active', max_length=256),
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
        migrations.DeleteModel(
            name='OSFamily',
        ),
    ]
